import Head from "next/head";
import styles from '../styles/Home.module.css'
const About = () => {
    return ( 
    <>
        <Head><title>Avengers | About </title></Head>
        <div>
            <h1 className={styles.new}>About</h1>
            <p>The Avengers are a team of fictional superheroes and the protagonists of the Marvel Cinematic Universe (MCU) media franchise, based on the Marvel Comics team of the same name created by Stan Lee and Jack Kirby in 1963. Founded by S.H.I.E.L.D. Director Nick Fury, the team is a United States-based organization composed primarily of superpowered and gifted individuals, described as "Earth's Mightiest Heroes", who are committed to the world's protection from a variety of threats. The Avengers are depicted as operating in the state of New York: originally from the Avengers Tower in Midtown Manhattan and subsequently in the Avengers Compound in Upstate New York. Arranged as an ensemble of core MCU characters originally consisting of Tony Stark / Iron Man, Steve Rogers / Captain America, Thor, Bruce Banner / Hulk, Natasha Romanoff / Black Widow, and Clint Barton / Hawkeye, it later expands to include 16 total members. Regarded as an important part of the franchise, they are central to the MCU's first 23 films, collectively known as the Infinity Saga. The Avengers from alternate universes were depicted in subsequent MCU properties across the Multiverse Saga, including appearances in the Disney+ animated series What If...? (2021–present) and Doctor Strange in the Multiverse of Madness (2022). The Avengers are set to return in Avengers: Doomsday (2026) and Avengers: Secret Wars (2027). Both films will be part of the MCU's Phase Six, concluding the Multiverse Saga.

Following the formation Marvel Studios as an independent film studio by Avi Arad, the head of Marvel's film division, producer Kevin Feige envisioned creating a shared cinematic universe to introduce the Avengers, similar to Stan Lee and Jack Kirby's comic books in the 1960s. Once Feige became studio chief in 2007 and formed his creative team, his strategy involved creating individual films for each major character in Phase One, beginning with Iron Man (2008) and concluding with The Avengers (2012). Casting for the original six members occurred from 2006 to 2010, beginning with Robert Downey Jr. as Iron Man and concluding with Mark Ruffalo replacing Edward Norton as the Hulk by 2010. Successive MCU installments introduced new members, with actors from other MCU films reprising their roles. Following the financial and critical success of The Avengers, a sequel, Avengers: Age of Ultron (2015), was subsequently developed, with Aaron Taylor-Johnson and Elizabeth Olsen joining as Pietro and Wanda Maximoff, respectively. Then, Captain America: Civil War (2016) was gradually reworked into a film influenced by the "Civil War" comic storyline, depicting the Avengers's division and introducing Tom Holland as Peter Parker / Spider-Man. Avengers: Infinity War (2018) and Avengers: Endgame (2019) concluded the Infinity Saga and depicted their disbandment.

The four Avengers films are currently the third highest-grossing superhero franchise and the sixth highest-grossing film franchise of all time, grossing more than US$7.7 billion. The Avengers have received praise as a group from critics including their dynamic together, with Endgame received praise from critics as a conclusion for that iteration of the team. Due to their successful introduction, other film studios decided to create own shared superhero universes, notably DC Entertainment and Warner Bros. Pictures announcing plans to release a Justice League film. Avengers Campus, a series of attractions at various Disney Parks, opened in June 2021 at Disney California Adventure, while an immersive family dining experience called "Avengers: Quantum Encounter" debuted at the Worlds of Marvel restaurant in the Disney Wish cruise ship in July 2022.</p>
            <p>Three years after the Battle of New York, Hydra uses Loki's scepter following their infiltration of S.H.I.E.L.D.[10][11] The Avengers locate it in Sokovia, where they recover it and encounter twin superhuman Hydra test subjects, Wanda and Pietro Maximoff. Barton is wounded and Rogers captures Hydra leader Wolfgang von Strucker while Stark retrieves the scepter, despite being subjected to hallucinations by Wanda's telepathy. Stark and Banner unilaterally decide to use the scepter to create the Ultron Program, a sentient artificial intelligence (AI) peacekeeping force. However, Ultron resolves to eradicate humanity.[12]

In Africa, the Avengers fight Ultron, now allied with the Maximoffs. Wanda induces telekinetic hallucinations, triggering Banner's transformation into the Hulk before Barton stops her, while Stark stops Hulk's rampage with his Hulkbuster armor. After reconvening at Barton's farmhouse, Rogers, Barton, and Romanoff retrieve a new vibranium body created by Ultron. Stark and Banner use it to create Vision, a sentient and benevolent being powered from the Stark's J.A.R.V.I.S. program, Mjolnir, and the Mind Stone.[12][13] Ultron tries to use Sokovia as a meteor to cause an extinction event. The Avengers, joined by James Rhodes and the Maximoffs, defeat Ultron's sentries and evacuate civilians. Pietro sacrifices himself to save Barton,[14] while Stark and Thor destroy Sokovia, and Vision fully terminates Ultron to avert the event. In the aftermath, Stark and Barton retire, Banner disappears, and Thor decides to find the Infinity Stones, while Rhodes, Sam Wilson, Wanda, and the Vision join the team. The Avengers relocate their primary headquarters to the Avengers Compound in Upstate New York.[12]

Civil War
The cast of Civil War, Kevin Feige, the Russo brothers, and Nate Moore at the London premiere
The cast of Captain America: Civil War, joined by Kevin Feige, the directing Russo brothers and producer Nate Moore at the London premiere
Months after the Battle of Sokovia, the Avengers' new facility becomes targeted in a heist, with a skirmish between Wilson and Scott Lang.[15][16] In 2016, Rogers, Romanoff, Maximoff, and Wilson defend a research lab in Lagos from Brock Rumlow. They successfully stop Rumlow and his crew of mercenaries, but Maximoff's usage of telekinesis to try to save civilians kills Wakandan diplomats. Thus, United States Secretary of State Thaddeus Ross presents the Sokovia Accords, United Nations (U.N.) legislation intended to regulate superhumans' activities. The Avengers are divided: Stark, Rhodes, Vision, and Romanoff support it, while Rogers and Wilson object due to fears of authoritarianism.[17]

After Bucky Barnes is accused of killing Wakandan King T'Chaka, Rogers and Wilson protect him from an arrest warrant, causing them to clash with Stark, Rhodes, Romanoff, and T'Challa, T'Chaka's son. After Barnes is detained, Helmut Zemo activates Barnes' Winter Soldier persona using the Winter Soldier Book, although Barnes later recovers and reveals Zemo's interest in the Winter Soldier Program. To aid them, Wilson and Rogers recruit Lang and Barton, then take Maximoff out of confinement at the Avengers Compound. The divided Avengers meet and fight at the Leipzig/Halle Airport; Rogers, Barnes, Wilson, Barton, Lang, and Maximoff clash with Stark, Rhodes, Romanoff, Vision, T'Challa and new recruit Peter Parker.[17][18]

Rogers and Barnes escape with Romanoff's help, traveling to the Hydra Siberian Facility to stop Zemo from reactivating the Winter Soldier Program. Their teammates are imprisoned in the Raft and Rhodes' legs are paralyzed after accidentally being struck by Vision's blast. Stark joins Rogers and Barnes after realizing Barnes' innocence, but fights them after Zemo reveals Barnes' assassination of Stark's parents.[19] In the fight, Rogers disables Stark's armor and Barnes' cybernetic arm is destroyed. Rogers then abandons his shield. Meanwhile, T'Challa apprehends Zemo, realizing him to be T'Chaka's killer.[17] Rogers later frees his teammates from the Raft, becoming fugitives.[20] Barton and Lang agree to be under house arrest to be with their families.[21] Although officially reduced to just Stark, Vision, and Rhodes, the Avengers continue operating. Stark offers to hire Parker after he defeats Adrian Toomes. However, Parker declines, choosing to remain as Spider-Man, but promises to assist the Avengers if needed.[22] In 2018, Wade Wilson / Deadpool travels from his universe, Earth-10005, to Earth-616 / the "Sacred Timeline" hoping to join the Avengers and give his life added meaning. He is interviewed by Happy Hogan, who rejects him, and returns to his own universe.[23]

The Blip
"Infinity War (event)" redirects here. For other uses, see Infinity War (disambiguation).
In 2018, the Avengers come into conflict with Thanos and his children, who seek the six Infinity Stones to erase half of the universe's life. Thanos hijacks a spaceship containing Asgardian refugees, killing Loki and subduing Thor.[24][25][26] Thanos defeats Hulk, who is transported to Earth by Heimdall to inform Stephen Strange, the keeper of the Time Stone, of Thanos' arrival. Banner, Strange, and Wong, joined by Stark and Parker, confront two of his children in Greenwich Village. With Banner unable to transform to aid in the fight, Strange is captured and taken to their spaceship, while Banner warns Rogers of Thanos' intention to acquire Vision's Mind Stone.[21] Stark and Parker pursue Strange and board the spaceship, where Stark officially anoints Parker as an Avenger. They go to Titan to confront Thanos, allying with the Guardians of the Galaxy along the way. The two teams temporarily restrain Thanos in an ensuing battle to take his Infinity Gauntlet off, now with four Stones. However, Peter Quill hits Thanos after learning he killed Gamora, freeing and allowing Thanos to incapacitate the group. With Thanos preparing to kill Stark, Strange surrenders the Time Stone to save his life.[21]

Meanwhile, Maximoff and Vision, now in a relationship and hiding out in Edinburgh, are ambushed by two more of Thanos' children, resulting in Vision getting wounded. Rogers, Romanoff, and Wilson arrive and help. Returning to the Avengers Compound, they meet Rhodes and Banner to discuss Thanos. Vision proposes to be destroyed to prevent Thanos from acquiring the Mind Stone, but Maximoff refuses and the team travel to Wakanda, where Shuri begins an operation to safely remove the Stone. The Wakandan army, their allies, and Barnes aid the Avengers to repel an invasion by Thanos' children. Thor arrives on the battlefield alongside Rocket and Groot through the Bifrost after forging his new Stormbreaker axe on Nidavellir. Shuri is ambushed, stopping the operation, but the Avengers eventually kill Thanos' children. When Thanos arrives, the Avengers delay him while Maximoff kills Vision to destroy the Mind Stone. Maximoff is successful, but Thanos uses the Time Stone to undo her actions and retrieve the Stone, killing Vision again. With a full Gauntlet, Thanos initiates the Blip.[27] Wilson, Barnes, Maximoff, Strange, Parker, T'Challa, Groot, Quill, Drax, and Mantis are blipped, leaving Stark and Nebula stranded on Titan while Thanos escapes.[21] Fury and Maria Hill are blipped as they try to find the Avengers, but Fury manages to contact Danvers.[21] Barton's family also blipped during his house arrest, causing him to become vengeful vigilante Ronin and murder criminals.[28] Lang gets trapped in the Quantum Realm while harvesting energy, as Hank Pym, Hope, and Janet van Dyne get blipped prior to extracting him.[29].</p>
        </div>
    </>
     );
}
 
export default About;